#Build the application and the package it a docker iamge

steps:
#ensure the tests are running
- name: 'gcr.io/cloud-builders/mvn'
  args: ['verify']
  dir: 'app'

#package the application
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
  dir: 'app'

# create a docker container for the application  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/fooapp', '.']
  dir: 'app'

#saves it in the google registry
images: ['gcr.io/$PROJECT_ID/fooapp']