steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean verify package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/fooapp', '.']
images: ['gcr.io/$PROJECT_ID/fooapp']