#Build the application and the package it a docker iamge
steps:

##0 ensure the tests are running before packgint the application
#- name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
#  args: ['verify', 'package', '-q']
#  dir: 'app'
#
##2 create a docker container for the application
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '--tag=gcr.io/$PROJECT_ID/fooapp:latest', '.']
#  dir: 'app'

#3 run the testing environment
- name: 'docker/compose:1.15.0'
  args: ['up', '-d']
  dir: 'component-test'
  env:
    - 'PROJECT_ID=$PROJECT_ID'

#4 wait for the application to start
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/bash'
  args: ['-c', 'sleep 30']
  dir: 'component-test'

#5 check if the application has started
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/bash'
  args: ['-c', './waitApp.sh']
  dir: 'component-test'

#6 run the business and performance tests
- name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
  args: ['verify', 'gatling:execute']
  dir: 'component-test'

#saves it in the google registry
images: ['gcr.io/$PROJECT_ID/fooapp']

tags:
  - "CI"